export const entries=[
 {name:'Before Meta',painting:'/art/cards/early-object-v1.png',dates:'2016–2024',role:'Building things on my own',heading:'It started with sneaker bots.',body:'At 16, I built bots to automate sneaker reselling. That grew into a six-figure business and helped pay for college. The Capital District is also where I discovered my love for research.',detail:'I studied computer science at UAlbany while running the business. I also worked on research and built software at Regeneron.',facts:[['2020–2024','B.S. in Computer Science from UAlbany, summa cum laude'],['2023','Software Engineer at Regeneron'],['2024','NSF Research Fellow at Data Management and Mining Lab','https://www.cs.albany.edu/~petko/lab/']],link:'#work',linkText:'Work & contact',z:1.7,stop:8,x:-5.9,inset:'business'},
 {name:'Meta',painting:'/art/cards/meta-object-v1.png',relatedProjects:[['Llama 4','https://ai.meta.com/blog/llama-4-multimodal-intelligence/'],['Gaia2','https://ai.meta.com/research/publications/are-scaling-up-agent-environments-and-evaluations/'],['Muse Spark','https://ai.meta.com/blog/introducing-muse-spark-msl/']],dates:'2024–2026',role:'Data → agents → superintelligence',heading:'Data for models and agents.',body:'I joined Meta in May 2024, working on code generation and AI safety data. Within six months, I was leading a team.',detail:'I later worked on data strategy for agent research, then on human feedback for model training.',facts:[['May–Nov 2024','Code generation & AI safety data'],['Nov 2024–Jul 2025','Agent evaluation & training environments'],['Jul 2025–Feb 2026','Human feedback for model training']],link:'#work',linkText:'Work & contact',z:-36.85,stop:-29,x:6.9,inset:'timeline'},
 {name:'Fleet AI',painting:'/art/cards/fleet-object-v1.png',dates:'February–June 2026',role:'Member of Technical Staff',heading:'RL environments at Fleet.',body:'As a Member of Technical Staff at Fleet AI, I built reinforcement learning environments where agents learned to use software with human supervision.',detail:'I worked there from February through June 2026, before joining Mercor.',facts:[['Feb–Jun 2026','Member of Technical Staff · Fleet AI']],link:'#work',linkText:'Work & contact',z:-84.55,stop:-77,x:5.9,inset:'environment'},
 {name:'Mercor',painting:'/art/cards/mercor-object-v1.png',dates:'June 2026–present',role:'Member of Technical Staff',heading:'Synthetic data for RL environments.',body:'I’m a Member of Technical Staff at Mercor, working on synthetic data for reinforcement learning environments.',detail:'My work focuses on synthetic data for reinforcement learning environments.',facts:[['Jun 2026–present','Member of Technical Staff · Mercor']],link:'mailto:me@mpaglia.com',linkText:'me@mpaglia.com',z:-103.6,stop:-96,x:-5.9,inset:'current'}
];

export const rlChapter={
 heading:'Reinforcement learning environments.',
 body:'I research how to generate high-quality data at scale for training AI agents. My work at Mercor and Fleet AI spans the tasks agents attempt, the environments they work in, and how their work is assessed.',
 role:'Member of Technical Staff',
 roles:[entries[3],entries[2]]
};
